valuesFilePath: ./values.yml

resources:
  - name: jfrogClientGoRepoSource
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitIntegration }}
      path: {{ .Values.repoPath }}
      branches:
        include: dev
      buildOn:
        commit: true

pipelines:
  - name: jfrog_go_client_push
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u18node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          RESOLVE_REPO: npm-virtual
    steps:
      - name: pre_run
        type: Bash
        configuration:
          inputResources:
            - name: jfrogClientGoRepoSource
        execution:
          onStart:
            - add_run_variables isPullRequest=$res_jfrogClientGoRepoSource_isPullRequest
      - name: static_code_analysis
        type: Bash
        configuration:
          inputSteps:
            - name: pre_run
          integrations:
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClientGoRepoSource
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - task: testtask@v0.0.2
              input:
                resourceName: $step_triggered_by_resource_name
                checks: "all, -SA1019, -ST1000, -ST1003, -ST1020, -ST1021, -ST1022"
      - name: go_sec
        type: Bash
        configuration:
          integrations:
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: pre_run
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - task: gosec@v0.0.1
              input:
                resourceName: $step_triggered_by_resource_name
                excludeRules: G204,G301,G302,G304,G306
                commandArgs: -exclude-dir=\.*test\.*
      - name: Frogbot_Fix
        type: Bash
        configuration:
          condition: 'isPullRequest == "false"'
          integrations:
            - name: jfrogPlatform
            - name: LeelaGitHub
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: pre_run
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - task: frogbot@v0.0.1
              id: frogbot_test
              input:
                repository: "leela-dev/jfrog-client-go"
                platformAccessTokenIntegration: "jfrogPlatform"
                resourceName: "jfrogClientGoRepoSource"
                botAction: "create-fix-pull-requests"
      - name: Frogbot_Scan_PR
        type: Bash
        configuration:
          condition: 'isPullRequest == "true"'
          requiresApproval: true
          integrations:
            - name: jfrogPlatform
            - name: LeelaGitHub
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: pre_run
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            # Run frogbot task
            - task: frogbot@v0.0.1
              id: frogbot_test
              input:
                repository: "leela-dev/jfrog-client-go"
                platformAccessTokenIntegration: "jfrogPlatform"
                resourceName: "jfrogClientGoRepoSource"
                botAction: "scan-pull-request"
      - name: lint
        type: Bash
        configuration:
          integrations:
            - name: int_default_artifactory
            - name: EcoSysSecrets
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: pre_run
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - cd $res_jfrogClientGoRepoSource_resourcePath
            - go vet -v ./...
      - name: artifactory_tests
        type: Matrix
        stepMode: Bash
        configuration:
          environmentVariables:
            JF_URL: $int_int_default_artifactory_url
            RTLIC: $int_EcoSysSecrets_RTLIC
            GOPROXY: direct
          integrations:
            - name: int_default_artifactory
            - name: EcoSysSecrets
            - name: jfrogPlatform
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: lint
          multiNode: true
        stepletMultipliers:
          nodePools:
            - default-dynamic-nodepool
            - windows_dynamic
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - echo $int_jfrogPlatform_url
            - cd $res_jfrogClientGoRepoSource_resourcePath
            - go install github.com/jfrog/jfrog-testing-infra/local-rt-setup@latest
            - ~/go/bin/local-rt-setup
            - go test -v github.com/jfrog/jfrog-client-go/tests --timeout 0 --test.artifactory --ci.runId=${operating_system}-artifactory
      - name: ds_xr_access_tests
        type: Matrix
        stepMode: Bash
        configuration:
          environmentVariables:
            JF_URL: $int_int_default_artifactory_url
            GOPROXY: direct
          integrations:
            - name: jfrogPlatform
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: lint
          multiNode: true
        stepletMultipliers:
          nodePools:
            - default-dynamic-nodepool
            - windows_dynamic
          environmentVariables:
            - suite : distribution
            - suite : xray
            - suite : access
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - cd $res_jfrogClientGoRepoSource_resourcePath
            - go test -v github.com/jfrog/jfrog-client-go/tests --timeout 0 --test.${suite} --rt.url=$int_int_default_artifactory_url --ds.url=$int_jfrogPlatform_url/distribution --xr.url=$int_jfrogPlatform_url/xray --access.url=$int_jfrogPlatform_url/access --rt.user=$int_int_default_artifactory_user --rt.password=$int_int_default_artifactory_apikey --access.token=$int_jfrogPlatform_accessToken --ci.runId=${operating_system}-${suite}
      - name: pipeline_tests
        type: Bash
        configuration:
          environmentVariables:
            JF_URL: $int_int_default_artifactory_url
            GOPROXY: direct
          integrations:
            - name: jfrogPlatform
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: lint
          nodePool: default-dynamic-nodepool
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - cd $res_jfrogClientGoRepoSource_resourcePath
            - go test -v github.com/jfrog/jfrog-client-go/tests --timeout 0 --test.pipelines --rt.url=$int_int_default_artifactory_url --pipe.url=$int_jfrogPlatform_url/pipelines --rt.user=$int_int_default_artifactory_user --rt.password=$int_int_default_artifactory_apikey --pipe.accessToken=$int_jfrogPlatform_accessToken --pipe.vcsToken=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 --pipe.vcsRepo=$res_jfrogClientGoRepoSource_gitRepoFullName --pipe.vcsBranch=$res_jfrogClientGoRepoSource_branchName --ci.runId=${operating_system}_pipe
      - name: jfrog_client_go_repositories_tests
        type: Bash
        configuration:
          integrations:
            - name: int_default_artifactory
            - name: EcoSysSecrets
          inputResources:
            - name: jfrogClientGoRepoSource
          inputSteps:
            - name: lint
          environmentVariables:
            JF_URL: $int_int_default_artifactory_url
            GOPROXY: direct
            RTLIC: $int_EcoSysSecrets_RTLIC
          nodePool: default-dynamic-nodepool
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - cd $res_jfrogClientGoRepoSource_resourcePath
            - go install github.com/jfrog/jfrog-testing-infra/local-rt-setup@latest
            - ~/go/bin/local-rt-setup
            - go test -v github.com/jfrog/jfrog-client-go/tests --timeout 0 --test.repositories