resources:
  - name: jfrogClient
    type: GitRepo
    configuration:
      gitProvider: LeelaGitHub
      path: leela-dev/jfrog-client-go
      buildOn:
        pullRequestCreate: true
pipelines:
  - name: jfrog_client_go_tests
    configuration:
      jfrogCliVersion: 2
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog/pipelines-u18node
            tag: "16"
            autoPull: true
      environmentVariables:
        readOnly:
          RESOLVE_REPO: npm-virtual
    steps:
      - name: unlabel_pr
        type: Bash
        execution:
          onExecute:
            - echo "Need to check the ways to do this"
      - name: go_cache
        type: Bash
        configuration:
          inputSteps:
            - name: unlabel_pr
        execution:
          onExecute:
            - echo "TBD"
      - name: lint
        type: Bash
        configuration:
          integrations:
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClient
          inputSteps:
            - name: unlabel_pr
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - cd $res_jfrogClient_resourcePath
            - go vet -v ./...
      - name: artifactory_tests
        type: Matrix
        stepMode: Bash
        configuration:
          environmentVariables:
            JF_URL: $int_int_default_artifactory_url
            GOPROXY: direct
          integrations:
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClient
          inputSteps:
            - name: lint
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - suite : artifactory
              os: ubuntu-latest
            - suite : artifactory
              os: macos-latest
            - suite : artifactory
              os: windows-latest
#          nodePools:
#            - windows
#            - ubuntu_18
#            - ubuntu_16
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
          onExecute:
            - cd $res_jfrogClient_resourcePath
            - go install github.com/jfrog/jfrog-testing-infra/local-rt-setup@latest
            - ~/go/bin/local-rt-setup
            - go test -v github.com/jfrog/jfrog-client-go/tests --timeout 0 --test.artifactory --ci.runId=${os}-${suite}
      - name: pipeline_tests
        type: Matrix
        stepMode: Bash
        configuration:
          environmentVariables:
            JF_URL: $int_int_default_artifactory_url
            GOPROXY: direct
          integrations:
            - name: jfrogPlatform
            - name: int_default_artifactory
          inputResources:
            - name: jfrogClient
          inputSteps:
            - name: lint
          multiNode: true
        stepletMultipliers:
          environmentVariables:
            - suite : artifactory
              os: ubuntu-latest
            - suite : artifactory
              os: macos-latest
            - suite : artifactory
              os: windows-latest
#          nodePools:
#            - windows
#            - ubuntu_18
#            - ubuntu_16
        execution:
          onStart:
            - task: jfrog/setup-go@v0.0.2
              input:
                version: "1.19.3"
                cacheIntegration: int_default_artifactory
            - go version
            - go env GOPATH
            - cd $res_jfrogClient_resourcePath
            - go vet -v ./...
          onExecute:
            - cd $res_jfrogClient_resourcePath
            - go install github.com/jfrog/jfrog-testing-infra/local-rt-setup@latest
            - go test -v github.com/jfrog/jfrog-client-go/tests --timeout 0 --test.pipelines --rt.url=$int_int_default_artifactory_url/artifactory --pipe.url=$int_int_default_artifactory_url/pipelines --rt.user=$int_int_default_artifactory_user --rt.password=$int_int_default_artifactory_apikey --pipe.accessToken=$int_jfrogPlatform_accessToken --pipe.vcsToken=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 --pipe.vcsRepo=$res_jfrogClient_gitRepoFullName --pipe.vcsBranch=$res_jfrogClient_branchName --ci.runId=${os}_pipe







